/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-04-17

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f3xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	// Enable TIM7 clock
			RCC->APB1ENR |= RCC_APB1ENR_TIM7EN;

			// Reset TIM6 configuration
			TIM7->CR1 = 0x0000;
			TIM7->CR2 = 0x0000;

			// Set TIM7 prescaler
			// Fck = 8MHz -> /8 = 100kHz counting frequency
			TIM7->PSC = (uint16_t) 0; //79

			// Set TIM7 auto-reload register for 1ms
			TIM7->ARR = (uint16_t) 100; //99

			// Enable auto-reload preload
			TIM7->CR1 |= TIM_CR1_ARPE;

			// Enable Interrupt upon Update Event
			TIM7->DIER |= TIM_DIER_UIE;

			// Start TIM7 counter
			TIM7->CR1 |= TIM_CR1_CEN;


			// Set priority level 1 for TIM6 interrupt
				NVIC_SetPriority(TIM7_DAC2_IRQn, 1);

				// Enable TIM6 interrupts
				NVIC_EnableIRQ(TIM7_DAC2_IRQn);

  /* TODO - Add your application code here */
  while (1)
  {
  }

  return 0;
}


void TIM7_DAC2_IRQHandler()
{
	// Test for TIM6 update pending interrupt
	if ((TIM7->SR & TIM_SR_UIF) == TIM_SR_UIF)
	{
		// Clear pending interrupt flag
		TIM7->SR &= ~TIM_SR_UIF;

		// Do what you need

	}
}
